---
- name: check for projects location
  file: path={{ projects_dir }} state=directory mode=0755

- name: update dev
  git: repo={{ item.repo }} dest={{ projects_dir }}/{{ item.dest }} version={{ item.version }}
  with_items:
    - { repo: "git@github.com:roosta/utils.git",     dest: "utils",     version: "master" }
    - { repo: "git@github.com:roosta/LS_COLORS.git", dest: "LS_COLORS", version: "master" }
    - { repo: "git@github.com:roosta/colors.git",    dest: "colors",    version: "master" }

- name: symlink project files.
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - { src: "{{ projects_dir }}/utils",                    dest: "~/utils" }
    - { src: "{{ projects_dir }}/colors",                   dest: "~/colors" }
    - { src: "{{ projects_dir }}/LS_COLORS/LS_COLORS",      dest: "~/.dircolors" }
    - { src: "{{ projects_dir }}/utils/chdisp_nvidia.sh",   dest: "{{ bin_dir }}/chdisp" }
    - { src: "{{ projects_dir }}/utils/bakc.sh",            dest: "{{ bin_dir }}/bakc" }
    - { src: "{{ projects_dir }}/utils/touchpad_toggle.sh", dest: "{{ bin_dir }}/touchpad_toggle" }
